lineageControllerWebhook:
  image: ghcr.io/cozystack/cozystack/lineage-controller-webhook:v1.0.0-rc.2@sha256:ea4fc38d2fb0ed82d6488989b6bbf061c2f619d5583f28da0b9e0e48859bf94b
  debug: false
  localK8sAPIEndpoint:
    enabled: true
  # nodeSelector for the DaemonSet
  # Talos uses empty value: "node-role.kubernetes.io/control-plane": ""
  # Generic k8s (k3s, kubeadm) uses: "node-role.kubernetes.io/control-plane": "true"
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
