piraeusServer:
  image:
    repository: ghcr.io/cozystack/cozystack/piraeus-server
    tag: 1.32.3@sha256:aa97f39d90c0726b587f0a376504f13d1f308adeb42db7d98cec9ac7de237361
# Talos-specific workarounds (disable for generic Linux like Ubuntu/Debian)
talos:
  enabled: true
linstor:
  autoDiskful:
    enabled: true
    minutes: 30
    allowCleanup: true
linstorCSI:
  image:
    repository: ghcr.io/cozystack/cozystack/linstor-csi
    tag: v1.10.5@sha256:753cab64259ec51e6f4976749b8d4ef4db7c92f877416b00231af251142908d8
