backupController:
  image: "ghcr.io/cozystack/cozystack/backup-controller:v1.0.0-rc.2@sha256:7bdd5139b1a286c55ba127614b2a8c46362f98ef274a77971cb8ba4ca83fe3d4"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
