cozystackController:
  image: ghcr.io/cozystack/cozystack/cozystack-controller:v1.0.0-rc.2@sha256:0af82dbcec16d6544c9f61a6e7ecfdd3990370ae41b5cd4e124eda72ec794a26
  debug: false
  disableTelemetry: false
