kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v1.0.0-rc.2@sha256:79522b1bc911418a65e28e1c80efe363d4dd35156dad55aacdb732d2922c6ceb
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v1.0.0-rc.2@sha256:79522b1bc911418a65e28e1c80efe363d4dd35156dad55aacdb732d2922c6ceb
