backupStrategyController:
  image: "ghcr.io/cozystack/cozystack/backupstrategy-controller:v1.0.0-rc.2@sha256:e6304af0a7354a11244ef56516b7ab9736e8047e36bd5271a3cbce961cd8f8df"
  replicas: 2
  debug: false
  metrics:
    enabled: true
    bindAddress: ":8443"
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
